on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  export_game:
      runs-on: ubuntu-latest
      name: Export game
      steps:
      - name: checkout
        uses: actions/checkout@v2.1.0

      - name: export
        uses: firebelley/godot-export@v3.0.0
        with:
          base_version: 0.1.0
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.4/Godot_v3.4.4-stable_export_templates.tpz
          relative_project_path: ./
          create_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}