on:
  push:
    branches:
      - master

jobs:
  export_game:
      runs-on: ubuntu-latest
      name: Export game
      steps:
      - name: checkout
        uses: actions/checkout@v2.1.0

      - name: Insert Leaderboard API Key
        env:
          LEADERBOARD_API_KEY: ${{ secrets.SILENTWOLF_LEADERBOARD_API_KEY }}
        run: |
          sed -i "s/{{LEADERBOARD_API_KEY}}/${{ env.LEADERBOARD_API_KEY }}/" project.godot

      - name: export
        uses: firebelley/godot-export@v3.0.0
        with:
          base_version: 1.1.0
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.5/Godot_v3.5-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.5/Godot_v3.5-stable_export_templates.tpz
          relative_project_path: ./
          create_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
